export enum ActionEvent {
  SELECT_ALL_EXCHANGE_LINES,
  SEND_LINES_TO_EDITOR,
  CLEAR_ALL_EXCHANGE_LINES,
  SPLITTER_BUTTON_TOGGLE,
  EDITOR_SELECT_ALL,
  EDITOR_CLEAR_ALL,
  EDITOR_GENERATE,
  GENERATE_FILE_TREE,
  FILE_TREE_ADD_FOLDER,
  FILE_TREE_ADD_DOCUMENT,
  FILE_TREE_ADD_ROOT_FOLDER,
}
