version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: ['npm', 'start']

  frontend:
    build:
      context: ./frontend
      dockerfile: tools/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "4200:4200"
    command: ['ng', 'serve', '--host', '0.0.0.0', '--port', '4200', '--poll', '2000']

  mongo-dev:
    image: mongo:latest
    volumes:
      - mongo-dev-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpass

  nginx:
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongo-dev-data:
