version: '3.0'
services:
  backend:
    image: 437884575683.dkr.ecr.us-east-1.amazonaws.com/backend:latest
#    volumes:
#      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    image: 437884575683.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
#    volumes:
#      - ./frontend:/app
    environment:
      - NODE_ENV=production

  nginx:
    image: 437884575683.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
