@hostname = http://localhost:4200

###
# @name ping
POST {{hostname}}/api/login
content-type: application/json

{
    "email": "test",
    "password": "test-password"
}

###
# @name email-submission
POST {{hostname}}/api/submit-email
content-type: application/json

{
    "email": "test-client-email"
}