@hostname = http://localhost:4200

###
# @name ping
GET {{hostname}} HTTP/1.1
content-type: application/json

###

curl http://localhost:4200

###
# @name ping
POST {{hostname}}/sage-page-app/login
content-type: application/json

{
    "email": "test",
    "password": "test-password"
}

###
# @name email-submission
GET {{hostname}}/api/test
content-type: application/json

{
    "email": "test-client-email"
}



@hostname = http://localhost:3000

###
# @name ping
POST {{hostname}}/sage-page-app/login
content-type: application/json

{
    "email": "test",
    "password": "test-password"
}

###
# @name email-submission
GET {{hostname}}/api/test
content-type: application/json

{
    "email": "test-client-email"
}