import { Component, OnInit } from '@angular/core';
import { DropdownModule } from 'primeng/dropdown';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { InputTextareaModule } from 'primeng/inputtextarea';
import { InputTextModule } from 'primeng/inputtext';
import { ButtonModule } from 'primeng/button';
import { RippleModule } from 'primeng/ripple';
import { ChatService } from './chat.service';
import { ExchangeComponent } from './exchange/exchange.component';
import { NgForOf } from '@angular/common';
import { StateManagementService } from '../../shared/services/state-management.service';
import { parseText } from './text-parser/text-parser';
import { Line } from '../shared/models/line';
import { EventBusService } from '../../shared/services/event-bus.service';

const testResponse2 = `
It seems like you're performing a test or possibly seeking information on how to write or format content. Here's an example of both an outline and a wiki article format to help you understand how you could present information in either style. I'll use a generic topic, "Renewable Energy", for demonstration purposes.

---
**Outline Format Example:**

I. Introduction to Renewable Energy
   A. Definition
   B. Importance

II. Types of Renewable Energy
   A. Solar Power
      1. How it works
      2. Benefits
   B. Wind Power
      1. How it works
      2. Benefits
   C. Hydropower
      1. How it works
      2. Benefits
   D. Geothermal Energy
      1. How it works
      2. Benefits
   E. Biomass Energy
      1. How it works
      2. Benefits

III. Advantages of Renewable Energy
   A. Environmental Impact
   B. Sustainability
   C. Economic Benefits

IV. Challenges of Renewable Energy
   A. Cost
   B. Geography and Weather Dependencies
   C. Storage

V. Future of Renewable Energy
   A. Technological Innovations
   B. Policy and Investment
   C. Global Trends

VI. Conclusion
   A. Summary
   B. Call to Action

---
`;

const testResponse3 = `
**Wiki Article Format Example:**

# Renewable Energy

## Introduction
Renewable energy refers to energy that is collected from renewable resources, which are naturally replenished on a human timescale, such as sunlight, wind, rain, tides, waves, and geothermal heat. The growing emphasis on minimizing the environmental impact and increasing energy security has popularized renewable energy worldwide.

## Types of Renewable Energy

### Solar Power
Solar power is harnessed from sunlight. Photovoltaic cells convert sunlight directly into electricity. **Benefits** include generating clean energy and reducing electricity bills.

### Wind Power
Wind turbines convert wind energy into electricity. **Benefits** include being a clean fuel source and requiring little maintenance once installed.

### Hydropower
Generated by the movement of water in rivers and dams. **Benefits** include a high efficiency and a renewable supply from the water cycle.

### Geothermal Energy
Comes from heat stored beneath the earth's surface. **Benefits** include a low emission level and a reliable energy source independent of the weather.

### Biomass Energy
Produced from organic materials, both plant and animal. **Benefits** include reducing dependence on fossil fuels and promoting waste reduction.

## Advantages and Challenges

### Advantages
- **Environmental Impact**: Significantly lower greenhouse gas emissions.
- **Sustainability**: Infinite energy supply from natural resources.
- **Economic Benefits**: Job creation in new energy markets.

### Challenges
- **Cost**: High initial investments.
- **Geography and Weather Dependencies**: Efficiency varies by location and weather.
- **Storage**: Difficulty in storing energy for use when production is low.

## Future of Renewable Energy
The future looks promising with advancements in technology, policy changes, and increased investment focusing on overcoming current challenges and maximizing the potential of renewable energy sources.

## Conclusion
As the world progresses towards more sustainable energy solutions, renewable energy plays a pivotal role in shaping our environmental, economic, and social landscape. Supporting renewable energy initiatives and technology advancements can significantly contribute to a cleaner, more sustainable future for all.

---

I hope these examples help you understand the difference between an outline and a wiki article format. If you have a specific topic in mind, I can tailor the content more closely to your requirements.
  `;

const testResponse = `
# Generative AI and the Revolution in Knowledge Management

Generative AI, with its unprecedented capabilities to understand, process, and produce human-like text, is poised to revolutionize the field of knowledge management. This technological frontier offers new ways to capture, organize, and disseminate organizational knowledge, transforming traditional approaches. We delve into the mechanisms through which generative AI will bring about this transformation, highlighting its impacts and potential applications in knowledge management.

## Introduction

Knowledge management (KM) encompasses the processes of creating, sharing, using, and managing the knowledge and information of an organization. It is a multidisciplinary approach to achieving organizational objectives by making the best use of knowledge. With the advent of generative artificial intelligence (AI), the landscape of KM is undergoing a substantial shift, promising to make knowledge processes more efficient, intuitive, and scalable.

## The Impact of Generative AI on Knowledge Management

### Enhanced Data Capture and Curation

- **Automated Content Creation**: Generative AI can automatically produce summaries, reports, and documentation, reducing manual efforts and time spent on these tasks.
- **Dynamic Knowledge Bases**: It can update knowledge bases dynamically by assimilating new information, ensuring that the organization’s knowledge repository remains current and comprehensive.

### Improved Information Retrieval

- **Semantic Search**: Generative AI enhances search capabilities by understanding the context and semantics behind queries, providing more accurate and relevant results.
- **Personalized Responses**: AI can tailor information retrieval to the individual user’s context, history, and preferences, streamlining access to knowledge.

### Facilitation of Knowledge Sharing and Collaboration

- **Language Translation and Synthesis**: By breaking down language barriers, generative AI facilitates the sharing of knowledge across global teams.
- **Automated Insights Generation**: It can analyze vast datasets to unearth insights, trends, and patterns, fostering informed decision-making and innovation.

### Learning and Development

- **Customized Learning Materials**: Generative AI can create personalized learning and training content based on an individual’s role, learning pace, and knowledge gaps.
- **Interactive Learning Assistants**: AI-powered assistants can provide real-time answers, explanations, and support, enhancing the learning experience.

## Potential Applications

1. **Automated Documentation**: Automate the creation of standard operating procedures, manuals, and reports, streamlining compliance and training processes.
2. **Intelligent Knowledge Repositories**: Build self-updating knowledge bases that organize and categorize information using natural language processing and understanding.
3. **Expert Systems**: Develop AI systems that encapsulate expert knowledge and provide consultancy and decision support in specialized domains.
4. **AI-driven Customer Support**: Implement AI chatbots and virtual assistants that provide instant access to knowledge bases for customer queries, improving service quality and efficiency.

## Challenges and Considerations

While the benefits are vast, integrating generative AI into knowledge management systems comes with its set of challenges, including data privacy concerns, the need for accurate and bias-free AI models, and the requirement for substantial initial investment in technology and training. Moreover, organizations must navigate the ethical considerations associated with automating knowledge work, ensuring human oversight and maintaining job satisfaction among employees.

## Conclusion

Generative AI heralds a new era in knowledge management, offering tools and methodologies to enhance efficiency, improve accessibility, and foster innovation. By intelligently automating repetitive tasks, personalizing learning and development, and enabling more effective knowledge sharing, this technology paves the way for organizations to achieve a competitive advantage in the knowledge economy. However, its successful implementation will require careful planning, ethical considerations, and a clear strategy to integrate human and artificial intelligence collaboratively in the knowledge management process.
`

export interface Exchange {
  query: string;
  response: string | null;
  lines: Line[] | null;
}

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [
    DropdownModule,
    FormsModule,
    ReactiveFormsModule,
    InputTextareaModule,
    InputTextModule,
    ButtonModule,
    RippleModule,
    ExchangeComponent,
    NgForOf,
  ],
  templateUrl: './chat.component.html',
  styleUrl: './chat.component.scss',
})
export class ChatComponent {
  chatModels = ['GPT3', 'GPT4'];
  selectedModel = 'GPT4';
  exchanges!: Exchange[];
  queryText!: string;

  constructor(
    private chatService: ChatService,
    private stateService: StateManagementService,
    private eventBus: EventBusService,
  ) {
    this.exchanges = this.stateService.getState('exchanges') || [];
  }

  onButtonClick(query: string) {
    console.log('button clicked');

    if (query == 'test') {
      return this.handleTestResponse('How will generative AI revolutionize knowledge management.');
    }

    this.exchanges.push({
      query: query,
      response: null,
      lines: null,
    });

    this.chatService.sendQuary(query).subscribe(
      (response) => {
        this.handleResponse(query, response);
      },
      (error) => {
        console.error('Error:', error);
      },
    );
  }

  handleResponse(query: string, response: any) {
    const content = response.choices[0].message.content;
    console.log('Response:', content);
    this.exchanges.pop();
    this.exchanges.push({
      query: query,
      response: content,
      lines: parseText(content),
    });
    this.stateService.saveState('exchanges', this.exchanges);
  }

  handleTestResponse(query: string) {
    return this.handleResponse(query, {
      choices: [
        {
          message: {
            content: testResponse,
          },
        },
      ],
    });
  }

  handleTextareaKeyDown($event: KeyboardEvent) {
    if ($event && $event.key === 'Enter' && !$event.shiftKey) {
      $event.preventDefault();
      this.onButtonClick(this.queryText);
      this.queryText = '';
    }
  }
}
