name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          sudo ln -s /usr/bin/python3 /usr/bin/python
          pip3 install --upgrade pip

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Get ECR login password
        id: ecr-login
        run: |
          ECR_PASSWORD=$(aws ecr get-login-password --region us-east-1)
          echo "::set-output name=password::$ECR_PASSWORD"

      - name: Docker login
        run: |
          echo ${{ steps.ecr-login.outputs.password }} | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REGISTRY }}

      - name: Build and push Docker image
        run: |
          docker build -t my-docker-image .
          docker tag my-docker-image:latest ${{ secrets.DOCKER_REGISTRY }}/my-docker-image:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/my-docker-image:latest
